# Generated by Django 4.0.5 on 2022-09-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feeds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('protein', models.FloatField()),
                ('energy', models.FloatField()),
                ('lysine', models.FloatField()),
                ('methionine', models.FloatField()),
                ('e_extract', models.FloatField()),
                ('c_fiber', models.FloatField()),
                ('calcium', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('a_phosphorus', models.FloatField()),
                ('pythic_phosphorus', models.FloatField()),
                ('salt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('protein', models.FloatField()),
                ('energy', models.FloatField()),
                ('lysine', models.FloatField()),
                ('methionine', models.FloatField()),
                ('e_extract', models.FloatField()),
                ('c_fiber', models.FloatField()),
                ('calcium', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('a_phosphorus', models.FloatField()),
                ('pythic_phosphorus', models.FloatField()),
                ('salt', models.FloatField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
