# Generated by Django 4.0.5 on 2022-09-26 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdetails',
        ),
    ]
